# Practice Numpy for CHILLA

In [ ]:
import numpy as np
arr=np.arange(1,51)
arr

In [ ]:
arr_2d = arr.reshape(10,5)
arr_2d

In [ ]:
#  Slicing 
arr_2d[6:8,2:4]

In [ ]:
ar1= np.arange(1,12)
ar1

In [ ]:
multiples_of_5=(arr_2d % 5) == 0
# multiples_of_5
arr_2d[multiples_of_5]

### You cannot perform computational expressions on List but it is possible with Numpy arrays

In [ ]:
arr=np.arange(1,50,5)
arr

In [ ]:
arr = arr - 1
arr 

In [ ]:
new_arr = arr / 5

In [ ]:
new_arr.astype("int32")

In [ ]:
new_arr.argsort()

In [ ]:
randarray= np.random.randint(1,50,50)
randarray

In [ ]:
randarray

In [ ]:
randarray.reshape(5,10)

In [ ]:
randarray.T

# NUMPY EXERCISES

In [70]:
#  Create an array of 10 Zeros

import numpy as np
zeros= np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [71]:
# Create an array of 10 ones

import numpy as np
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [72]:
# Create an array of 10 fives

fives = ones * 5
fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [73]:
# Create an array of 10 fives

fivees = (np.ones(10))*5
fivees

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [74]:
# Create an array of integers ranging from 10,50

rang = np.arange(10,51)
rang

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [83]:
# Create an array of all the even integers from 10 to 50

array1 = np.arange(10,51)
new= (array1 % 2) == 0
# array1(evens)
evens = array1[new]
evens

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [84]:
# Create an array of all the even integers from 10 to 50

np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [85]:
#  Create a 3X3 matrix for integers between 0 to 8

np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [122]:
# Create a 3X3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [123]:
#  Use numpy to generate a random number between 0 and 1

np.random.rand(1)

array([0.99494748])

In [95]:
# Use  numpy to generate random 25 numbers array

np.random.randn(25)

array([-0.16429789,  0.34911505,  0.15229831,  1.18452127, -1.92391759,
        0.33685389, -0.52730766,  1.88194633, -0.45594927,  0.37975763,
       -0.16166831, -0.80709583,  0.83780561,  0.1078719 ,  0.29143575,
        0.83699037,  1.72384092,  1.03589829, -0.56391272,  1.02912302,
       -1.34486978, -1.20113845, -1.12963739,  0.43654817,  1.1152315 ])

In [124]:
#  Create the matrix
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [106]:
# Create an array of 20 linearly spaced points between 0 and 1

np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and Selection

In [107]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [108]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [109]:
mat[3,4]

20

In [111]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [113]:
mat[-1,:]

array([21, 22, 23, 24, 25])

In [115]:
mat[-2:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [116]:
# Sum of all the values in mat
mat.sum()

325

In [117]:
#  standard deviation of mat 
mat.std()

7.211102550927978

In [119]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])